### ISSUE TITLE
Update the CDVN repo with the mainnet configuration

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon-distributed-validator-node#212] opened 2023-07-20 08:27 UTC
## 🎯 Problem to be solved

The CDVN  repository lacks the updated mainnet configuration. This can lead to inconsistencies and potential issues when deploying or managing the mainnet environment.

## 🛠️ Proposed solution

The solution to this issue is to update the CDVN repository with the latest mainnet configuration. This will ensure that the repository accurately reflects the current state of the mainnet environment, thereby minimizing the risk of configuration-related issues. It will also provide a single source of truth for the mainnet configuration, making it easier for team members to understand and manage the environment. The person responsible for this task should ensure that all changes are properly documented and communicated to the team to avoid any confusion.

**Comment by corverroos** [comment] 2023-07-24 12:16
mmmm, it isn't very clear what exactly is missing... I presume some specific inconsistencies where discovered, it would be great to add them here to the ticket

**Comment by boulder225** [comment] 2023-08-10 15:02
> Being ready for mainnet, and defaulting to mainnet are different. I'm not sure CDVN should default to mainnet, we want to keep its use to a minimum in production imo.

**Comment by dB2510** [comment] 2023-12-01 07:07
Duplicate of #235 and is closed by #237

**Closed by dB2510** 2023-12-01 07:07 UTC
Labels: bug, protocol, postmortem, PM-5, needs refining
